version: '3'
services:
  php:
    container_name: lemp_php
    build: php/
    image: lemp30_php
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html/
    expose:
      - "8888"
    depends_on:
      - db

  nginx:
    container_name: lemp30_nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    volumes:
      - ./html/:/var/www/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: www.devop30.com
    networks:
      - webproxy
      - default

  db:
    container_name: lemp30_mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=devops101
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101
  pma:
    container_name: lemp30_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - webproxy
      - default
    environment:
      VIRTUAL_HOST: mydb.devop30.com
    expose:
      - "80"

networks:
  default:
    external:
      name:
        web30_network
  webproxy:
    external:
      name:
        proxy30_network
