version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx30proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    external:
      name: proxy30_network
